CREATE TABLE KOPO_REGION_MASTER_JI
(
REGIONID VARCHAR2(100),
REGIONNAME VARCHAR2(100));

TRUNCATE TABLE KOPO_REGION_MASTER_JI;

SELECT * FROM KOPO_PRODUCT_VOLUME;

SELECT * FROM KOPO_REGION_MASTER_JI;

EDIT KOPO_REGION_MASTER_JI;

EDIT KOPO_PRODUCT_VOLUME;

SELECT * FROM
KOPO_REGION_MASTER_JI A
INNER JOIN KOPO_PRODUCT_VOLUME B
ON A.REGIONID = B.REGIONID