-- 테이블 생성

CREATE TABLE KOPO_PRODUCT_VOLUME_JI(
    REGIONID VARCHAR2(20),
    PRODUCTGROUP VARCHAR2(20),
    YEARWEEK VARCHAR2(20),
    QTY NUMBER);
    
SELECT * FROM KOPO_PRODUCT_VOLUME_JI;

-- 생성된 테이블 구조 변경    
ALTER TABLE KOPO_PRODUCT_VOLUME_JI
    ADD CONSTRAINTS KOPO_PRODUCT_VOLUME_JI_PK      --CONSTRAINTS라는 기본키를 추가하겠다는 뜻
    PRIMARY KEY (REGIONID, PRODUCTGROUP, YEARWEEK);
    
--테이블 컬럼 이름 변경하기(ALTER TABLE RENAME)
ALTER TABLE KOPO_PRODUCT_VOLUME_JI RENAME COLUMN QTY TO VOLUME;

-- 테이블에 있는 데이터 지우기
TRUNCATE TABLE KOPO_PRODUCT_VOLUME_HK2;

-- 데이터 삽입
INSERT INTO KOPO_PRODUCT_VOLUME_JI
    VALUES('A01', 'ST0001', '201702', 50);

    
CREATE TABLE REGION_MASTER_JI
(
    REGIONID VARCHAR2(100),
    REGIONNAME VARCHAR2(100),
    CONSTRAINT PK_REGION_MASTER_JI 
    PRIMARY KEY(REGIONID, REGIONNAME),
    CONSTRAINT FK_REGION_MASTER_JI
    FOREIGN KEY(REGIONID) REFERENCES KOPO_PRODUCT_VOLUME_JI(REGIONID));

SELECT * FROM REGION_MASTER_JI;

TRUNCATE TABLE REGION_MASTER_JI;

INSERT INTO REGION_MASTER_JI VALUES('A01','한국');

SELECT * FROM REGION_MASTER_JI