/* Formatted on 2019/06/17 오후 2:44:22 (QP5 v5.318) */

-- 201918 주차에 201918주차 예측
SELECT A.PRD_SEG1,
       A.PRD_SEG2,
       A.PRD_SEG3,
       'D603_ACT_FCST' AS MEASUREID,
       '201918'        AS PLANWEEK,                            --201918주차에 돌렸다
       YEAR || WEEK    AS TARGETWEEK,             --201918주차에 201918주차를 예측했을 때
       QTY,                                                           --QTY의 값
       OUTFCST                                                    --OUTFCST의 값
  FROM PRO_FCST_RESULT_1WEEK A;

SELECT * FROM PRO_FCST_RESULT_1WEEK;

-- 201917 주차에 201917주차 이후 예측

SELECT * FROM PRO_FCST_RESULT_2WEEK;

-- JOIN에는 2가지 방식이 있음
---실적

SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW;

---기준정보 (지역 마스터)

SELECT * FROM KOPO_REGION_MST;

--- INNER JOIN (ANSI: 미국산업표준 조인방법임)

SELECT A.*, B.REGIONNAME
  FROM KOPO_CHANNEL_SEASONALITY_NEW  A
       INNER JOIN KOPO_REGION_MST B ON A.REGIONID = B.REGIONID;

--- LEFT JOIN (ANSI: 미국산업표준 조인방법임)

SELECT A.*, B.REGIONNAME
  FROM KOPO_CHANNEL_SEASONALITY_NEW  A
       LEFT JOIN KOPO_REGION_MST B ON A.REGIONID = B.REGIONID;

--- 오라클에서만 사용가능한 문법

SELECT A.*, B.REGIONNAME
  FROM KOPO_CHANNEL_SEASONALITY_NEW A, KOPO_REGION_MST B
 WHERE A.REGIONID = B.REGIONID;

--전체 경우의수 조인
--1-1.
SELECT A.*, B.*
FROM CUSTOMERDATA A
,CUSTOMER_NAME B;

--1-2
SELECT A.*, B.*
FROM CUSTOMERDATA A
CROSS JOIN CUSTOMER_NAME B;

-- INNER 조인
--2-1.
SELECT A.*, B.*
FROM CUSTOMERDATA A
,CUSTOMER_NAME B
WHERE 1=1
AND A.CUSTID = B.CUSTID;

--2-2.
SELECT A.*, B.*
FROM CUSTOMERDATA A
INNER JOIN CUSTOMER_NAME B
ON 1=1
AND A.CUSTID = B.CUSTID;

-- LEFT 조인
--3-1.
SELECT A.*, B.*
FROM CUSTOMERDATA A
,CUSTOMER_NAME B
WHERE 1=1
AND A.CUSTID = B.CUSTID(+);

--3-2.
SELECT A.*, B.*
FROM CUSTOMERDATA A
LEFT JOIN CUSTOMER_NAME B
ON 1=1
AND A.CUSTID = B.CUSTID(+);

--FULL OUTER 조인
--4-1.
SELECT A.*, B.*
FROM CUSTOMERDATA A
,CUSTOMER_NAME B
WHERE 1=1
AND A.CUSTID(+) = B.CUSTID(+);

--4-2.
SELECT A.*, B.*
FROM CUSTOMERDATA A
FULL OUTER JOIN CUSTOMER_NAME B
ON 1=1
AND A.CUSTID = B.CUSTID;

--RIGHT 조인
---5-1.
SELECT A.*, B.*
FROM CUSTOMERDATA A
,CUSTOMER_NAME B
WHERE 1=1
AND A.CUSTID(+) = B.CUSTID;

SELECT A.*, B.*
FROM CUSTOMERDATA A
RIGHT JOIN CUSTOMER_NAME B
ON 1=1
AND A.CUSTID = B.CUSTID;


--카티션 곱 조인
SELECT A.*, B.*
FROM CUSTOMERDATA A
,CUSTOMER_NAME B;

SELECT * FROM CUSTOMERDATA;

SELECT * FROM CUSTOMER_NAME