SELECT * FROM PRO_FCST_RESULT_1WEEK;

SELECT * FROM PRO_FCST_RESULT_2WEEK;

SELECT * FROM PRO_FCST_RESULT_5WEEK;

-- STEP1. 각 테이블(1주차~6주차) PLANWEEK 생성
---1-1. 13주차 테이블 PLANWEEK 생성
CREATE TABLE
    PRO_FCST_RESULT_6WEEK_13 AS
SELECT
    PRD_SEG1,
    PRD_SEG2,
    PRD_SEG3,
    '201913' AS PLANWEEK,
    YEAR,
    WEEK,
    QTY,
    OUTFCST
FROM PRO_FCST_RESULT_6WEEK
WHERE 1=1 
AND YEAR='2019'
AND WEEK='18';

SELECT * FROM PRO_FCST_RESULT_6WEEK_13;

DROP TABLE PRO_FCST_RESULT_6WEEK_13;

-- 1-2.14주차 PLANWEEK
CREATE TABLE
    PRO_FCST_RESULT_5WEEK_14 AS
SELECT
    PRD_SEG1,
    PRD_SEG2,
    PRD_SEG3,
    '201914' AS YEARWEEK,
    YEAR,
    WEEK,
    QTY,
    OUTFCST
FROM PRO_FCST_RESULT_5WEEK
WHERE 1=1
AND YEAR='2019'
AND WEEK='18';

--- 1-3. 15주차 PLANWEEK
CREATE TABLE
    PRO_FCST_RESULT_4WEEK_15 AS
SELECT 
    PRD_SEG1,
    PRD_SEG2,
    PRD_SEG3,
    '201915' AS PLANWEEK,
    YEAR,
    WEEK,
    QTY,
    OUTFCST
FROM PRO_FCST_RESULT_4WEEK
WHERE 1=1
AND YEAR='2019'
AND WEEK='18';

--- 1-4. 16주차 PLANWEEK
CREATE TABLE
    PRO_FCST_RESULT_3WEEK_16 AS
SELECT
    PRD_SEG1,
    PRD_SEG2,
    PRD_SEG3,
    '201916' AS PLANWEEK,
    YEAR,
    WEEK,
    QTY,
    OUTFCST
FROM PRO_FCST_RESULT_3WEEK
WHERE 1=1
AND YEAR='2019'
AND WEEK='18';

--- 1-5. 17주차 PLANWEEK
CREATE TABLE
    PRO_FCST_RESULT_2WEEK_17 AS
SELECT
    PRD_SEG1,
    PRD_SEG2,
    PRD_SEG3,
    '201917' AS PLANWEEK,
    YEAR,
    WEEK,
    QTY,
    OUTFCST
FROM PRO_FCST_RESULT_2WEEK
WHERE 1=1
AND YEAR = '2019'
AND WEEK = '18';

--- 1-6. 18주차 PLANWEEK
CREATE TABLE
    PRO_FCST_RESULT_1WEEK_18 AS
SELECT
    PRD_SEG1,
    PRD_SEG2,
    PRD_SEG3,
    '201918' AS PLANWEEK,
    YEAR,
    WEEK,
    QTY,
    OUTFCST
FROM PRO_FCST_RESULT_1WEEK
WHERE 1=1
AND YEAR='2019'
AND WEEK='18';

SELECT * FROM PRO_FCST_RESULT_6WEEK_13;

-- STEP2. PLANWEEK생성한 테이블들을 합치기
SELECT * FROM
    (
        SELECT * FROM PRO_FCST_RESULT_6WEEK_13
        UNION SELECT * FROM 
            PRO_FCST_RESULT_5WEEK_14
        UNION SELECT * FROM
            PRO_FCST_RESULT_4WEEK_15
        UNION SELECT * FROM
            PRO_FCST_RESULT_3WEEK_16
        UNION SELECT * FROM
            PRO_FCST_RESULT_2WEEK_17
        UNION SELECT * FROM
            PRO_FCST_RESULT_1WEEK_18
            )
PIVOT(
    SUM(OUTFCST)
    FOR PLANWEEK IN
    ('201913' AS W6,
    '201914' AS W5,
    '201915' AS W4,
    '201916' AS W3,
    '201917' AS W2,
    '201918' AS W1)
    )
ORDER BY PRD_SEG1, PRD_SEG2, PRD_SEG3;
    

    



