--데이터 조회하기--
SELECT * FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP IN ('ST0001', 'ST0002')
AND YEARWEEK BETWEEN 201501 AND 201530 --BETWEEN
AND YEARWEEK LIKE '%2015%' --LIKE
AND YEARWEEK IS NOT NULL; --NULL값이 아닌 값


-- A01 지역의 201724~25 201727~29
-- AP1NAME = BEST BUY, HOME DEPOT
-- PRODUCTGROUP = HHP

-- 연산자 사용하여 조회하기
SELECT * FROM KOPO_CHANNEL_RESULT
WHERE 1=1
AND (YEARWEEK BETWEEN 201724 AND 201725
OR YEARWEEK BETWEEN 201727 AND 201729) --OR조건 잘 숙지하기
AND AP1NAME IN ('BEST BUY', 'HOME DEPOT')
AND PRODUCT LIKE '%HHP%'
AND AP2ID IN ('A01');

-- 사용자 조건 입력 받아 출력하기
SELECT
    REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGREOUP = &PRODUCT
OR YEARWEEK = '201544';

-- TARGETWEEK 컬럼에 대한 시작, 종료 2개의 사용자 변수 입력받아 데이터 조회
SELECT * FROM KOPO_PROMOTION
WHERE 1=1
AND TARGETWEEK BETWEEN &START_WEEK AND &END_WEEK;

-- 정렬하기
SELECT
    REGIONID,
    PRODUCTGROUP,
    YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = 'ST0001'
AND YEARWEEK BETWEEN 201501 AND 201503
ORDER BY YEARWEEK DESC, REGIONID ASC; --DESC : 내림차순, ASC : 오름차순

-- 지역, 상품, 주차 오름차순 형태로 조회
SELECT
    REGIONID,
    PRODUCTGROUP,
    YEARWEEK
FROM KOPO_PRODUCT_VOLUME
ORDER BY REGIONID ASC, PRODUCTGROUP ASC, YEARWEEK ASC;




