SELECT * FROM KOPO_PRODUCT_VOLUME;

--조건절 이용하여 데이터 조회하기 VER.1
SELECT --SELECT * FROM으로 안하는 이유 : 나중에 새로운 컬럼을 추가했을 때 에러가 발생할 수 있기 때문
    REGIONID, 
    PRODUCTGROUP, 
    YEARWEEK, 
    VOLUME
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0002'
AND (YEARWEEK = '201515'
OR YEARWEEK = '201516');

--조건절 이용하여 데이터 조회하기 VER.2
SELECT
    REGIONID, 
    PRODUCTGROUP, 
    YEARWEEK, 
    VOLUME
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0002'
AND YEARWEEK >= '201515'
AND YEARWEEK <= '201516';

--산술 연산자 사용하기--
--ORACLE은 문자든 숫자든 곱하기 연산이 됨--
--ROUND연산 : 소수점 제거
SELECT
    REGIONID,
    PRODUCTGROUP,
    YEARWEEK,
    VOLUME,
    ROUND(VOLUME * 1.1, 0) AS WEIGHTED_VOLUME --VOLUME에 1.1을 곱한 후 소수점 첫째자리에서 반올림하여 WEIGHTED_VOLUME컬럼명으로 조회(원래 데이터에 생성되는건 아님)
FROM KOPO_PRODUCT_VOLUME
WHERE 1=1
AND PRODUCTGROUP = 'ST0001'
AND YEARWEEK >= '201501';

SELECT * FROM KOPO_PROMOTION;

-- PMAP에 10% 할인된 가격 ROUND처리하여 PMAP10 생성 --
SELECT
    REGIONID,
    ITEM,
    TARGETWEEK,
    PLANWEEK,
    MAP_PRICE,
    IR,
    PMAP,
    PRODUCT,
    ROUND(PMAP-(PMAP * 0.1), 0) AS PMAP10
FROM KOPO_PROMOTION;

-- PMAP/MAP_PRICE 비율 구하여 PERCENT 컬럼 생성 VER.1--
SELECT
    REGIONID,
    ITEM,
    TARGETWEEK,
    PLANWEEK,
    MAP_PRICE,
    IR,
    PMAP,
    PRODUCT,
    NVL(PMAP/NULLIF(MAP_PRICE, 0),0) AS PERCENT
FROM KOPO_PROMOTION;

-- PMAP/MAP_PRICE 비율 구하여 PERCENT 컬럼 생성 VER.2 --
SELECT A.*,
    CASE WHEN A.MAP_PRICE = 0
            THEN 0 --MAP_PRICE가 0이면 구하지 않을거야
         WHEN A.MAP_PRICE IS NULL
            THEN 0 --MAP_PRICER가 NULL이면 구하지 않을거야
         ELSE A.PMAP/A.MAP_PRICE END AS PRO_PERCENT
FROM KOPO_PROMOTION A; --별칭 붙여주기