-- 대/소문자 변경하기
--TEST FROM DUAL은 테스트해볼수 있는 틀
SELECT LOWER('AAAA') AS TEST FROM DUAL; 

-- 컬럼 값 함치기(CONCAT 및 OR연산)
SELECT
    CONCAT(REGIONID,CONCAT('_',PRODUCT)) AS KEYCOL1,
    REGIONID||'_'||PRODUCT AS KEYCOL2
FROM KOPO_CHANNEL_SEASONALITY_NEW;

-- 컬럼 값 추출하기(SUBSTR)
SELECT
    PRODUCT,
    SUBSTR(PRODUCT,1,7) --PRODUCT라는 문자열에 1번째부터 7번째 자리까지 추출
FROM KOPO_CHANNEL_SEASONALITY_NEW;

-- 컬럼 값 채우기(LPAD, RPAD)
SELECT
    LPAD(PRODUCT, 10, '0')
    FROM KOPO_CHANNEL_SEASONALITY_NEW;

-- CUSTOMERCODE를 12자리로 조회
-- 12자리가 안될경우 앞에 *로 채우기
SELECT
    LPAD(CUSTOMERCODE, 12, '*')
    FROM KOPO_CUSTOMERDATA;
    
-- 컬럼 값 제거(LTRIM, RTRIM, TRIM)
SELECT
PRODUCT,
    TRIM(PRODUCT), --PRODUCT에서 공백을 모두 지우겠다
    LTRIM(PRODUCT, 'PRO'), --PRODUCT에서  왼쪽의 'PRO'를 지우겠다
    RTRIM(PRODUCT, '56')
FROM KOPO_CHANNEL_SEASONALITY_NEW;
    
-- 변경하기(REPLACE)
SELECT
    REGIONID,
    REPLACE(REGIONID,'A','REGION')
FROM KOPO_CHANNEL_SEASONALITY_NEW;

-- 고객코드 10자리가 아니면 왼쪽에 0으로 채우기
-- 이후 고객코드의 뒷 4자리는 암호화를 위해 * 처리
SELECT * FROM KOPO_CUSTOMERDATA;

SELECT
    CUSTOMERCODE,
    LPAD(CUSTOMERCODE, 10, '0') AS STEP1, --LAPD(컬럼명, 자릿수, '붙일문자')
    REPLACE(LPAD(CUSTOMERCODE, 10, '0'),SUBSTR(LPAD(CUSTOMERCODE, 10, '0'),7,10),'****')
FROM KOPO_CUSTOMERDATA;